import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Set up a cache for navigation requests
const fileExtensionRegexp = new RegExp('/[^/?]+.[^/]+$');
registerRoute(({ request, url }) => {
    // Return true if we're requesting a navigation to a new document
    return (
        request.mode === 'navigate' ||
        (!request.headers.get('accept')?.includes('text/html') && url.pathname === '/')
    );
}, createHandlerBoundToURL(process.env.BASE_URL + 'index.html'));

// Cache API requests
registerRoute(
    ({ url }) => url.origin === 'https://seu-magento.com.br' && url.pathname.startsWith('/rest'),
    new StaleWhileRevalidate({
        cacheName: 'magento-api',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    })
);
